name: Publish One Click Apps

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: actions/upload-pages-artifact@v3.0.1


        with:
          node-version: 14
      - run: npm ci && npm run formatter-write && npm run build

  
      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: Caprover One Click
          path: "./dist"
          if-no-files-found: error
